### ISSUE TITLE
Error runing clean_esmond_db.sh

### ISSUE THREAD

**Issue by nuqleo** [esnet/esmond#48]
There is error when running script clean_esmond_db.sh from perfsonar-toolkit-3.5.1:
# ./clean_esmond_db.sh

Traceback (most recent call last):
  File "./util/ps_remove_data.py", line 72, in <module>
    from esmond.api.perfsonar.api import EVENT_TYPE_CF_MAP, row_prefix, datetime_to_ts
ImportError: No module named api

This is what script runs:
# !/bin/bash

export ESMOND_ROOT=/usr/lib/esmond
export ESMOND_CONF=/etc/esmond/esmond.conf
export DJANGO_SETTINGS_MODULE=esmond.settings
cd $ESMOND_ROOT
source /opt/rh/python27/enable
. bin/activate
python ./util/ps_remove_data.py -c /etc/perfsonar/toolkit/clean_esmond_db.conf

I tried to make symlink /usr/lib/esmond/esmond/api/perfsonar/api.py -> api_v2.pyc
but then there was other error:
# ./clean_esmond_db.sh

cassandra_db [INFO] Checking/creating column families
cassandra_db [INFO] Schema check done
cassandra_db [DEBUG] Opening ConnectionPool
cassandra_db [INFO] Connected to ['localhost:9160']
Traceback (most recent call last):
  File "./util/ps_remove_data.py", line 72, in <module>
    from esmond.api.perfsonar.api import EVENT_TYPE_CF_MAP, row_prefix, datetime_to_ts
ImportError: cannot import name row_prefix

**Comment by nuqleo** [comment]
esmond updated today to esmond-2.0.1-1.el6.x86_64 but bug still not fixed.

**Comment by arlake228** [comment]
Appears to be fixed as of 2.1-2. At the very least I am unable to recreate on CentOS 6 or CentOS 7 anymore.
