### ISSUE TITLE
Merge the esmond_manage Debian patch upstream

### ISSUE THREAD

**Issue by tonin** [esnet/esmond#59]
In the Debian packages we use a script and a config file to setup the default esmond environment variables and use the correct Python version.  We should merge this patch upstream and use it in both CentOS6 and CentOS7 packages to help user create API keys and esmond account.

That would help streamline the esmond documentation, see https://github.com/perfsonar/docs/issues/24 for reference.

**Comment by vvidic** [comment]
If we could link the proposed ``esmond_manage`` script from ``/usr/bin/`` or ``/usr/sbin`` we could use the same documentation for CentOS and Debian.

**Comment by tonin** [comment]
Reopening because now that the script lives in master, we need to remove the Debian patches that exist in the debian/jessie and debian/wheezy branch.

**Comment by vvidic** [comment]
Debian packages updated and tested to work correctly. Also updated the esmond RPM package to create ``/usr/sbin/esmond_manage`` symlink so the script can be started by the root user. Documentation updated in the 4.0rc3 branch, let me know if the change should be copied to master.
