### ISSUE TITLE
Provide an easy esmond_manage script access

### ISSUE THREAD

**Issue by tonin** [esnet/esmond#61]
For both CentOS and Debian installation we now provide the `esmond_manage` script, see #59.  We should add the path to this script to $PATH or add a link in /usr/bin or /usr/sbin to the main script so that MA adminitrator can use this script easily.

Then we'd be able to streamline and harmonise http://docs.perfsonar.net/multi_ma_install.html much.

**Comment by vvidic** [comment]
Script linked in ``/usr/sbin/esmond_manage`` in RPM and Debian packages so the root user can start it. Documentation updated in the 4.0rc3 branch.
