### ISSUE TITLE
Remove version numbers in apache page listings and http headers

### ISSUE THREAD

**Issue by apertome** [esnet/esmond#62]
Remove version numbers in apache page listings and http headers

See here for context:

https://github.com/perfsonar/toolkit/issues/241

**Comment by arlake228** [comment]
Looking at this closer I can't find anywhere under the /esmond directory where this happens. I don't think its appropriate for esmond to change the root directory (which i don't think was suggested either) so i don't think there is anything to do. Closing.

**Comment by tonin** [comment]
One could argue there is the Django REST framework version number shown on top of each page...  Not sure how easy or difficult it is to hide.
