### ISSUE TITLE
Update esmond to support Django 1.10

### ISSUE THREAD

**Issue by vvidic** [esnet/esmond#64]
Debian 9 ships with Django 1.10 so esmond would need to be updated to work with that.

**Comment by vvidic** [comment]
Please review pull request #65 required to get esmond working with Django 1.10 on Debian 9/stretch. Django 1.10 also requires a newer version of netfields (0.5.3) to work correctly. Patched esmond also works with Django 1.8 on Debian 8/jessie.

**Comment by arlake228** [comment]
This works now. Spent a fair amount of time correcting unit tests and cleaning up dependencies when building from source, but works with 1.10 cleanly now, so closing.
